version: "3"
services:
    node:
      image: node:14
      restart: always
      ports:
        - 3000:3000
      volumes:
        - .:/usr/src/app
      networks:
        - nw-httpd
      command: 'npm start'
      working_dir: '/usr/src/app'
       
networks:
    nw-httpd:
        driver: bridge
        ipam:
            driver: default




  